apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stockmarket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dockerayush13/stockmarket-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/stockmarket
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stockmarket
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000